In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

In [6]:
onehot_repr=[one_hot(words,voc_size) for words in sent] 
# This means convert ever word into the voc =bulary size in the list sentences
print(onehot_repr)      

[[464, 113, 128, 291], [464, 113, 128, 310], [464, 275, 128, 151], [122, 153, 193, 104, 343], [122, 153, 193, 104, 339], [87, 464, 350, 128, 280], [308, 255, 375, 104]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 464 113 128 291]
 [  0   0   0   0 464 113 128 310]
 [  0   0   0   0 464 275 128 151]
 [  0   0   0 122 153 193 104 343]
 [  0   0   0 122 153 193 104 339]
 [  0   0   0  87 464 350 128 280]
 [  0   0   0   0 308 255 375 104]]


In [ ]:
## 10 feature dimesnions
dim=10
